smarter

diff --git a/.github/workflows/releases.yml b/.github/workflows/releases.yml
--- a/.github/workflows/releases.yml
+++ b/.github/workflows/releases.yml
@@ -27,7 +27,14 @@ jobs:
         with:
           java-version: '21'
           distribution: 'temurin'
-
+      - name: Validate release version
+        if: ${{ github.event.inputs.releaseVersion != '' }}
+        run: |
+          RELEASE=${{ github.event.inputs.releaseVersion }}
+          if [[ ! $RELEASE =~ ^[0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)?$ ]]; then
+            echo "Error: releaseVersion '$RELEASE' is not in the correct format x.y.z or x.y.z-SNAPSHOT"
+            exit 1
+          fi
       - name: Cache Gradle
         uses: actions/cache@v4
         with:
@@ -37,7 +44,6 @@ jobs:
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
           restore-keys: |
             ${{ runner.os }}-gradle-
-
       - name: Validate publishing secrets
         run: |
           if [ -z "${{ secrets.MAVEN_USER }}" ]; then
@@ -64,16 +70,21 @@ jobs:
         run: |
           if [ -n "${{ github.event.inputs.releaseVersion }}" ]; then
             VERSION="${{ github.event.inputs.releaseVersion }}"
+            echo "version=$VERSION" >> $GITHUB_OUTPUT
           elif [[ $GITHUB_REF == refs/tags/* ]]; then
             VERSION="${GITHUB_REF#refs/tags/v}"
+            echo "version=$VERSION" >> $GITHUB_OUTPUT
           else
             echo "Unable to determine version" >&2
-            exit 1
           fi
-          echo "version=$VERSION" >> $GITHUB_OUTPUT
-
       - name: Release with JReleaser
-        run: ./gradlew jreleaserFullRelease --info -Prelease -Pjreleaser.project.version=${{ steps.version.outputs.version }}
+        run: |
+          if [ -n "${{ steps.version.outputs.version }}" ]; then
+            PROP="-Pjreleaser.project.version=${{ steps.version.outputs.version }}"
+          else
+            PROP=""
+          fi
+          ./gradlew jreleaserFullRelease --info -Prelease $PROP
         env:
           JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
